# Generated by Django 4.2.30 on 2026-09-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("eve_sde", "0036_remove_star_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("transit", "Transit"),
                            ("export", "Export"),
                        ],
                        default="transit",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "ordering": ("solar_system__name",),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WorkforceRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Workforce allocated from this source."),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_routes",
                        to="aasov.plannedsystem",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_route",
                        to="aasov.plannedsystem",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("regions", models.ManyToManyField(blank=True, to="eve_sde.region")),
                (
                    "selected_systems",
                    models.ManyToManyField(blank=True, to="eve_sde.solarsystem"),
                ),
            ],
            options={
                "ordering": ("name",),
                "permissions": [("edit_plan", "Can edit sovereignty plans")],
            },
        ),
        migrations.CreateModel(
            name="PlannedUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("online", "Online"),
                            ("offline", "Offline"),
                        ],
                        default="planned",
                        max_length=7,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="aasov.plannedsystem",
                    ),
                ),
                (
                    "upgrade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="eve_sde.sovereigntyupgrade",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="plannedsystem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="systems",
                to="aasov.project",
            ),
        ),
        migrations.AddField(
            model_name="plannedsystem",
            name="solar_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="eve_sde.solarsystem"
            ),
        ),
        migrations.AddConstraint(
            model_name="workforceroute",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="aasov_route_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="workforceroute",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("destination")), _negated=True),
                name="aasov_route_distinct",
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedupgrade",
            constraint=models.UniqueConstraint(
                fields=("system", "upgrade"), name="aasov_system_upgrade_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedsystem",
            constraint=models.UniqueConstraint(
                fields=("project", "solar_system"), name="aasov_project_system_unique"
            ),
        ),
    ]
