# Generated by Django 5.2.17 on 2026-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aasov", "0001_initial"),
        ("eve_sde", "0036_remove_star_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ("name",),
                "permissions": [
                    ("edit_plan", "Can edit sovereignty plans"),
                    ("manage_plan", "Plan Manager: can remove systems from plans"),
                ],
            },
        ),
        migrations.AddField(
            model_name="plannedsystem",
            name="owner_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannedsystem",
            name="owner_kind",
            field=models.CharField(default="unknown", max_length=12),
        ),
        migrations.AddField(
            model_name="plannedsystem",
            name="owner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="plannedsystem",
            name="owner_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="excluded_systems",
            field=models.ManyToManyField(
                blank=True,
                related_name="excluded_sov_projects",
                to="eve_sde.solarsystem",
            ),
        ),
    ]
