# Generated by Django 5.2.17 on 2026-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aasov", "0002_alter_project_options_plannedsystem_owner_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedsystem",
            name="owner_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannedsystem",
            name="owner_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plannedsystem",
            name="owner_queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
