# Generated by Django 5.2.17 on 2026-09-24 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aasov", "0003_plannedsystem_owner_attempted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="capital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="aasov.plannedsystem",
            ),
        ),
    ]
