# Generated by Django 5.2.17 on 2026-09-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aasov", "0004_project_capital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedupgrade",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("online", "Online"),
                    ("temporary", "Temporary"),
                    ("offline", "Offline"),
                ],
                default="planned",
                max_length=9,
            ),
        ),
    ]
