# Generated by Django 5.2.17 on 2026-09-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aasov", "0005_alter_plannedupgrade_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_admins",
            field=models.BooleanField(
                default=False,
                help_text="Staff users with Can change project. Staff status alone is insufficient.",
                verbose_name="Administrators",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="allow_editors",
            field=models.BooleanField(default=False, verbose_name="Editors"),
        ),
        migrations.AddField(
            model_name="project",
            name="allow_managers",
            field=models.BooleanField(default=False, verbose_name="Plan Managers"),
        ),
        migrations.AddField(
            model_name="project",
            name="restrict_access",
            field=models.BooleanField(
                default=False,
                help_text="Unchecked: all viewers can access this project. Checked: only selected roles below (and superusers).",
                verbose_name="Restrict project access",
            ),
        ),
    ]
