# Generated by Django 5.2.17 on 2026-09-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aasov", "0006_project_allow_admins_project_allow_editors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="simplified_viewers",
            field=models.BooleanField(
                default=False,
                help_text="Viewers see only Online and Temporary upgrades, excluding power/workforce producers. Hide resource balances, fuel and workforce routes. Editors, Plan Managers and Administrators retain the full view.",
                verbose_name="Simplified view for Viewers",
            ),
        ),
    ]
